# Generated by Django 5.2.8 on 2025-11-24 04:54

from django.db import migrations

from apps.users.models import CustomUser


def create_default_user(apps, schema_editor):
    # Create a default superuser
    CustomUser.objects.get_or_create(username='system')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_language'),
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
