# Generated by Django 5.2.8 on 2026-07-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdadns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdapermissions',
            options={'managed': False, 'permissions': [('api_keys', "Allow's user to create and revoke their own API keys"), ('zones_view', 'View owned zones'), ('records_view', 'View records of owned zones'), ('records_create', 'Create records on owned zones'), ('records_delete', 'Delete records of owned zones'), ('records_edit', 'Edit records of owned zones')], 'verbose_name': 'PDA', 'verbose_name_plural': 'PDA'},
        ),
    ]
