# Generated by Django 5.2.8 on 2025-11-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_dns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='updated_at',
        ),
    ]
