# Generated by Django 5.2.8 on 2025-11-23 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_accounts", "0003_alter_account_name_alter_account_table_and_more"),
        ("api_dns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="record",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="zone",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_zones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated account for the zone",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="api_accounts.account",
            ),
        ),
    ]
