# Generated by Django 5.2.8 on 2025-11-24 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_dns", "0002_remove_record_created_at_remove_record_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zone",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("manage_zone_dnssec", "Can enable or disable DNSSEC for the zone"),
                    (
                        "manage_zone_records",
                        "Can create, update, or delete records in the zone",
                    ),
                    ("sync_zone", "Can sync zone data from PowerDNS"),
                ],
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
            },
        ),
        migrations.AddField(
            model_name="zone",
            name="soa_serial",
            field=models.PositiveBigIntegerField(
                blank=True,
                editable=False,
                help_text="SOA serial number",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4294967295),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="dnssec",
            field=models.BooleanField(default=False, help_text="Zone DNSSEC status"),
        ),
    ]
