# Generated by Django 5.2.8 on 2025-11-24 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_dns", "0003_alter_zone_options_zone_soa_serial_alter_zone_dnssec"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_zones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="dnssec",
            field=models.BooleanField(
                default=False, help_text="Zone DNSSEC status", max_length=255
            ),
        ),
    ]
