# Generated by Django 5.2.8 on 2025-11-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_dns', '0003_alter_zone_created_by_alter_zone_nameservers'),
        ('api_dns', '0004_alter_zone_created_by_alter_zone_dnssec'),
    ]

    operations = [
    ]
