# Generated by Django 5.2.8 on 2025-11-20 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zone name (e.g., example.com.)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid zone name format', regex='^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?)*\\.?$')])),
                ('account', models.CharField(help_text='Zone account (e.g., cappe)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid zone name format', regex='^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?)*\\.?$')])),
                ('dnssec', models.BooleanField(help_text='Zone DNSSEC status', max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('Native', 'Native'), ('Master', 'Master'), ('Slave', 'Slave')], default='Native', help_text='Zone kind (Native, Master, or Slave)', max_length=20)),
                ('nameservers', models.JSONField(default=list, help_text='List of nameserver hostnames')),
                ('server_id', models.CharField(default='localhost', help_text='PowerDNS server ID', max_length=100)),
                ('powerdns_id', models.CharField(blank=True, help_text='PowerDNS zone ID (cached from API)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'pdadns_zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Record name (relative to zone or FQDN)', max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('PTR', 'PTR'), ('SOA', 'SOA'), ('SRV', 'SRV'), ('CAA', 'CAA')], help_text='DNS record type', max_length=10)),
                ('content', models.TextField(help_text='Record content (value)')),
                ('ttl', models.IntegerField(default=3600, help_text='Time to live in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('disabled', models.BooleanField(default=False, help_text='Whether this record is disabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(help_text='Zone this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.zone')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'db_table': 'pdadns_records',
                'ordering': ['zone', 'name', 'record_type'],
                'unique_together': {('zone', 'name', 'record_type', 'content')},
            },
        ),
    ]
