# Generated by Django 5.2.8 on 2025-11-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_setting_zone_record'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='record',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
