# Generated by Django 5.2.8 on 2025-11-23 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(help_text='User id', max_length=255)),
                ('apikey', models.CharField(default='', help_text='Api key used', max_length=255)),
                ('api', models.BooleanField(default=False, help_text='Log from api')),
            ],
            options={
                'verbose_name': 'ActivityLog',
                'verbose_name_plural': 'ActivityLogs',
                'db_table': 'pdadns_activity',
                'ordering': ['id'],
            },
        ),
    ]
