# Generated by Django 5.2.8 on 2025-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.CharField(default='', help_text='Action taken by user or api_key', max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='details',
            field=models.CharField(default='', help_text='Details for activity', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.CharField(default='', help_text='User id', max_length=255),
        ),
    ]
