# Generated by Django 5.2.8 on 2025-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0002_activity_action_activity_details_alter_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='apikey',
            field=models.CharField(blank=True, default='', help_text='Api key used', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.CharField(blank=True, default='', help_text='User id', max_length=255),
        ),
    ]
