# Generated by Django 5.2.8 on 2025-11-23 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0003_alter_activity_apikey_alter_activity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp of activity'),
            preserve_default=False,
        ),
    ]
