# Generated by Django 5.2.8 on 2025-11-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0006_alter_activity_action'),
        ('api_activity', '0006_alter_activity_options_alter_activity_action'),
    ]

    operations = [
    ]
