# Generated by Django 5.2.8 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0007_merge_20251124_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('zone_create', 'Zone Create'), ('zone_update', 'Zone Update'), ('zone_delete', 'Zone Delete'), ('record_create', 'Record Create'), ('record_update', 'Record Update'), ('record_delete', 'Record Delete'), ('account_create', 'Account Create'), ('account_update', 'Account Update'), ('account_delete', 'Account Delete'), ('template_create', 'Template Create'), ('template_update', 'Template Update'), ('template_delete', 'Template Delete'), ('template_record_create', 'Template Record Create'), ('template_record_update', 'Template Record Update'), ('template_record_delete', 'Template Record Delete'), ('user_create', 'User Create'), ('user_update', 'User Update'), ('user_delete', 'User Delete'), ('group_create', 'Group Create'), ('group_update', 'Group Update'), ('group_delete', 'Group Delete'), ('user_login', 'User Login'), ('user_signup', 'User Signup'), ('user_apikey_create', 'User APIKey Create'), ('user_apikey_update', 'User APIKey Update'), ('user_apikey_delete', 'User APIKey Delete'), ('app_setting_change', 'App Setting Change'), ('clear_cache', 'Clear Cached Records and Zones')], default='', help_text='Action taken', max_length=255),
        ),
    ]
