# Generated by Django 5.2.8 on 2026-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0008_alter_activity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='info',
            field=models.CharField(default='', help_text='Info about activity', max_length=255),
        ),
    ]
