# Generated by Django 5.2.8 on 2025-11-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("globalSettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="globalsetting",
            table="global_settings",
        ),
    ]
