# Generated by Django 5.2.8 on 2025-11-20 22:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Account name (e.g., "cappe")', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid account name format', regex='^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?)*\\.?$')])),
                ('description', models.CharField(default='', help_text='Description for account', max_length=255)),
                ('contact', models.CharField(default='', help_text='Contact for account', max_length=255)),
                ('mail', models.CharField(default='', help_text='Mail contact info for account', max_length=255)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'pdadns_accounts',
                'ordering': ['id'],
            },
        ),
    ]
