# Generated by Django 5.2.8 on 2025-11-23 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mail',
            field=models.CharField(default='', help_text='Mail contact info for account', max_length=255, validators=[django.core.validators.EmailValidator(message='Invalid email address')]),
        ),
    ]
