# Generated by Django 5.2.8 on 2025-11-24 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0003_alter_account_name_alter_account_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, help_text='Account Members', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, help_text='Account owner', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='account_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
