# Generated by Django 5.2.8 on 2026-02-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'PDA Admin',
                'verbose_name_plural': 'PDA Admin',
                'permissions': [('zones_view', 'View zones'), ('zones_create', 'Create zones'), ('zones_delete', 'Delete zones'), ('zones_edit', 'Edit zones'), ('records_view', 'View records'), ('records_create', 'Create records'), ('records_delete', 'Delete records'), ('records_edit', 'Edit records'), ('users_view', 'View users'), ('users_manage', 'Manage users'), ('users_permissions', 'Manage user permissions'), ('users_groups', 'Manage user groups'), ('groups_view', 'View groups'), ('groups_manage', 'Manage groups'), ('groups_permissions', 'Manage group permissions'), ('accounts_view', 'View accounts'), ('accounts_manage', 'Manage accounts'), ('templates_view', 'View templates'), ('templates_manage', 'Manage templates'), ('activity_log_view', 'View activity log'), ('activity_log_details', 'View more details in activity log'), ('cache_flush', 'Flush cache'), ('settings', 'Settings for PDA'), ('dashboard', 'PDA Admin Dashboard')],
                'managed': False,
            },
        ),
    ]
