# Generated by Django 5.2.8 on 2026-07-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdaAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpermissions',
            options={'managed': False, 'permissions': [('zones_view', 'View zones'), ('zones_create', 'Create zones'), ('zones_delete', 'Delete zones'), ('zones_edit', 'Edit zones'), ('records_view', 'View records'), ('records_create', 'Create records'), ('records_delete', 'Delete records'), ('records_edit', 'Edit records'), ('users_view', 'View users'), ('users_create', 'Create users'), ('users_delete', 'Delete users'), ('users_edit', 'Edit users'), ('users_permissions', 'Manage user permissions'), ('users_groups', 'Manage user groups'), ('groups_view', 'View groups'), ('groups_create', 'Create groups'), ('groups_delete', 'Delete groups'), ('groups_edit', 'Edit groups'), ('groups_permissions', 'Manage group permissions'), ('accounts_view', 'View accounts'), ('accounts_create', 'Create accounts'), ('accounts_delete', 'Delete accounts'), ('accounts_edit', 'Edit accounts'), ('templates_view', 'View templates'), ('templates_create', 'Create templates'), ('templates_delete', 'Delete templates'), ('templates_edit', 'Edit templates'), ('activity_log_view', 'View activity log'), ('activity_log_details', 'View more details in activity log'), ('cache_flush', 'Flush cache'), ('settings', 'Settings for PDA'), ('dashboard', 'PDA Admin Dashboard')], 'verbose_name': 'PDA Admin', 'verbose_name_plural': 'PDA Admin'},
        ),
    ]
