# Generated by Django 5.2.8 on 2025-11-23 22:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default=None, help_text='Zone template name', max_length=255)),
                ('account', models.UUIDField(blank=True, default=None, null=True)),
                ('kind', models.CharField(choices=[('Native', 'Native'), ('Master', 'Master'), ('Slave', 'Slave')], default='Native', help_text='Zone kind (Native, Master, or Slave)', max_length=20)),
                ('nameservers', models.JSONField(default=list, help_text='List of nameserver hostnames')),
            ],
            options={
                'verbose_name': 'Zone template',
                'verbose_name_plural': 'Zone templates',
                'db_table': 'pdadns_templates_zones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Record name (relative to zone or FQDN)', max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('PTR', 'PTR'), ('SOA', 'SOA'), ('SRV', 'SRV'), ('CAA', 'CAA')], help_text='DNS record type', max_length=10)),
                ('content', models.TextField(help_text='Record content (value)')),
                ('ttl', models.IntegerField(default=3600, help_text='Time to live in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('zone_template', models.ForeignKey(help_text='Zone this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api_templates.zonetemplate')),
            ],
            options={
                'verbose_name': 'Record template',
                'verbose_name_plural': 'Record templates',
                'db_table': 'pdadns_templates_records',
                'ordering': ['zone_template', 'name', 'record_type'],
                'unique_together': {('zone_template', 'name', 'record_type', 'content')},
            },
        ),
    ]
