# Generated by Django 5.2.8 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtemplate',
            name='record_type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('AFSDB', 'AFSDB'), ('ALIAS', 'ALIAS'), ('CAA', 'CAA'), ('CERT', 'CERT'), ('CDNSKEY', 'CDNSKEY'), ('CDS', 'CDS'), ('CNAME', 'CNAME'), ('DNSKEY', 'DNSKEY'), ('DNAME', 'DNAME'), ('DS', 'DS'), ('HINFO', 'HINFO'), ('KEY', 'KEY'), ('LOC', 'LOC'), ('LUA', 'LUA'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('NSEC', 'NSEC'), ('NSEC3', 'NSEC3'), ('NSEC3PARAM', 'NSEC3PARAM'), ('OPENPGPKEY', 'OPENPGPKEY'), ('PTR', 'PTR'), ('RP', 'RP'), ('RRSIG', 'RRSIG'), ('SOA', 'SOA'), ('SPF', 'SPF'), ('SSHFP', 'SSHFP'), ('SRV', 'SRV'), ('TKEY', 'TKEY'), ('TSIG', 'TSIG'), ('TLSA', 'TLSA'), ('SMIMEA', 'SMIMEA'), ('TXT', 'TXT'), ('URI', 'URI')], help_text='DNS record type', max_length=10),
        ),
    ]
